# Generated by Django 4.0.6 on 2022-09-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(default=None, max_length=10)),
                ('schema', models.CharField(default=None, max_length=100000)),
            ],
        ),
    ]
